services:
  app:
    build:
      dockerfile: ./docker/python/Dockerfile
    command: sh run.sh
    ports:
      - 8000:8000
    working_dir: /usr/src/app
    volumes:
      - ./app:/usr/src/app:cached
    depends_on:
      - db

  db:
    image: mysql
    restart: always
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secure
      MYSQL_DATABASE: shop
