# Generated by Django 5.1.1 on 2024-10-28 11:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name_plural': ['categories']},
        ),
        migrations.AddField(
            model_name='product',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='owner_product', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
